title: Xenia Lew(刘昕尧)
description: A digital enthusiast, but also likes transportation
baseurl: ""
url: https://xenialew2004.github.io
# theme: cvless
remote_theme: piazzai/cvless

# site settings
taglong: A digital enthusiast, but also likes transportation
tagshort: digital enthusiast,transportation

# author settings
author:
  name: Xenia Lew(刘昕尧)
  email: xenialew@outlook.com
photo: assets/images/home/photo.jpg

# social media links
social:
  youtube: @xenialew
  facebook: profile.php?id=100091982108465
  github: XeniaLew2004
  instagram: l.liuxinyao
  email: xenialew@outlook.com
  email: xliu28308@gmail.com

# build settings
permalink: pretty

plugins:
  - jekyll-feed
